@startuml project-archiquecture
!include <cloudinsight/kafka>
!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites
!includeurl SPRITESURL/scala.puml
!theme vibrant
' left to right direction
' top to bottom direction

cloud OpenExchangeRates {
    component OpenExchangeRatesAPI{
        port "API" as openHTTPS
    }
}

cloud Finnhub {
    component FinnhubAPI {
        port "API" as finnHTTPS
    }
    component FinnhubWSS {
        port "WSS" as finnWSS
    }
}

node DockerEngine {
    rectangle "<$scala>" as Scala
    queue "<$kafka>" as Kafka

    node ProducerDocker

    Scala -- [ProducerDocker]
    Scala -- [ConsumerDocker]

    node ConsumerDocker {
        component [Spark Streaming]
        component [Email Service]
    }

    [ProducerDocker] -0)- [finnHTTPS]: consumes
    [ProducerDocker] -0)- [finnWSS]: consumes
    [ProducerDocker] -0)- [openHTTPS]: consumes

    [ProducerDocker] -right-> [Kafka]
    [Kafka] -up-> [Spark Streaming]

    [Spark Streaming] --> [Email Service]
}

@enduml
